[project]
name = "counter"
version = "0.1.0"
description = "Simple Kivy Counter"
readme = "README.md"
requires-python = ">=3.12,<3.13"

dependencies = [
    "kivy>=2.3.1",
]

[project.scripts]
counter = "counter.__main__:main"

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ksproject",
]

[tool.uv.sources]
ksproject = { git = "https://github.com/kivy-school/ksproject", rev = "master" }

[tool.kivy-school]
app_name = "Counter"
bootstrap = "kivy"

[tool.kivy-school.android]
package_name = "com.tjay.counter"

version_code = 1

archs = ["arm64-v8a"]

api = 36
sdk = "36"
min_api = 24
ndk = "28c"
ndk_api = 24

global_tools = true
byte_compile_python = true
