name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Buildozer and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip libtool autoconf automake build-essential
          pip install buildozer cython

      - name: Install Android Build-Tools and Accept Licenses
        run: |
          yes | /opt/hostedtoolcache/Python/3.11.13/x64/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.0"
          yes | /opt/hostedtoolcache/Python/3.11.13/x64/lib/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build the APK
        run: buildozer android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
